"""cascade swipe deletes

Revision ID: 18cc92c4fd62
Revises: 48f5e9757ce3
Create Date: 2025-11-24 01:43:55.464699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18cc92c4fd62'
down_revision: Union[str, None] = '48f5e9757ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('swipe_user_id_fkey', 'swipe', type_='foreignkey')
    op.drop_constraint('swipe_meal_id_fkey', 'swipe', type_='foreignkey')
    op.create_foreign_key(None, 'swipe', 'meal', ['meal_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'swipe', 'app_user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'swipe', type_='foreignkey')
    op.drop_constraint(None, 'swipe', type_='foreignkey')
    op.create_foreign_key('swipe_meal_id_fkey', 'swipe', 'meal', ['meal_id'], ['id'])
    op.create_foreign_key('swipe_user_id_fkey', 'swipe', 'app_user', ['user_id'], ['id'])
    # ### end Alembic commands ###
