"""Recomendation heuristic. Change swipe to have meal id

Revision ID: 3f3ac79c9a6e
Revises: 8cc2036de645
Create Date: 2025-11-23 22:42:00.117530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f3ac79c9a6e'
down_revision: Union[str, None] = '8cc2036de645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('computed_user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tag_prefs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('cuisine_prefs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('price_bin_prefs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('wait_bin_prefs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('computed_meal_features',
    sa.Column('meal_id', sa.UUID(), nullable=False),
    sa.Column('tag_vector', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('cuisine_vector', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('avg_wait_time', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meal_id')
    )
    op.drop_table('user_feed_item')
    op.add_column('swipe', sa.Column('meal_id', sa.UUID(), nullable=False))
    op.drop_constraint('unique_user_meal_session_swipe', 'swipe', type_='unique')
    op.create_unique_constraint('unique_user_meal_session_swipe', 'swipe', ['user_id', 'meal_id', 'session_id'])
    op.drop_constraint('swipe_meal_review_id_fkey', 'swipe', type_='foreignkey')
    op.create_foreign_key(None, 'swipe', 'meal', ['meal_id'], ['id'])
    op.drop_column('swipe', 'meal_review_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swipe', sa.Column('meal_review_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'swipe', type_='foreignkey')
    op.create_foreign_key('swipe_meal_review_id_fkey', 'swipe', 'meal_review', ['meal_review_id'], ['id'])
    op.drop_constraint('unique_user_meal_session_swipe', 'swipe', type_='unique')
    op.create_unique_constraint('unique_user_meal_session_swipe', 'swipe', ['user_id', 'meal_review_id', 'session_id'])
    op.drop_column('swipe', 'meal_id')
    op.create_table('user_feed_item',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('meal_review_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['meal_review_id'], ['meal_review.id'], name='user_feed_item_meal_review_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name='user_feed_item_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_feed_item_pkey'),
    sa.UniqueConstraint('user_id', 'meal_review_id', name='unique_user_feed_item')
    )
    op.drop_table('computed_meal_features')
    op.drop_table('computed_user_preferences')
    # ### end Alembic commands ###
