"""added core models

Revision ID: f521483e23d8
Revises: 885ec04d5cd8
Create Date: 2025-11-11 22:01:30.675566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f521483e23d8'
down_revision: Union[str, None] = '885ec04d5cd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_review',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('meal_name', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('waiting_time_minutes', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_vegan', sa.Enum('no', 'not specified', 'yes', name='vegan_status_enum'), server_default='not specified', nullable=False),
    sa.Column('is_halal', sa.Enum('no', 'not specified', 'yes', name='halal_status_enum'), server_default='not specified', nullable=False),
    sa.Column('is_vegetarian', sa.Enum('no', 'not specified', 'yes', name='vegetarian_status_enum'), server_default='not specified', nullable=False),
    sa.Column('is_spicy', sa.Enum('no', 'not specified', 'yes', name='spicy_status_enum'), server_default='not specified', nullable=False),
    sa.Column('is_gluten_free', sa.Enum('no', 'not specified', 'yes', name='gluten_free_status_enum'), server_default='not specified', nullable=False),
    sa.Column('is_dairy_free', sa.Enum('no', 'not specified', 'yes', name='dairy_free_status_enum'), server_default='not specified', nullable=False),
    sa.Column('is_nut_free', sa.Enum('no', 'not specified', 'yes', name='nut_free_status_enum'), server_default='not specified', nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='check_rating_range'),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('place_image',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_review_image',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meal_review_id', sa.UUID(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['meal_review_id'], ['meal_review.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swipe',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('meal_review_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('liked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['meal_review_id'], ['meal_review.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'meal_review_id', 'session_id', name='unique_user_meal_session_swipe')
    )
    op.create_index(op.f('ix_swipe_session_id'), 'swipe', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swipe_session_id'), table_name='swipe')
    op.drop_table('swipe')
    op.drop_table('meal_review_image')
    op.drop_table('place_image')
    op.drop_table('meal_review')
    op.drop_table('place')
    # ### end Alembic commands ###
