"""added is_synthetic to users

Revision ID: 77c7495694df
Revises: 159e599020da
Create Date: 2025-12-09 01:31:26.491919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77c7495694df'
down_revision: Union[str, None] = '159e599020da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_review', sa.Column('is_synthetic', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_review', 'is_synthetic')
    # ### end Alembic commands ###
