"""Add meals and other changes

Revision ID: 8cc2036de645
Revises: 198b6e548eb1
Create Date: 2025-11-23 19:01:31.190535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc2036de645'
down_revision: Union[str, None] = '198b6e548eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM meal_review")
    op.create_table('meal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('test_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('meal_review', sa.Column('meal_id', sa.UUID(), nullable=False))
    op.drop_constraint('meal_review_place_id_fkey', 'meal_review', type_='foreignkey')
    op.create_foreign_key(None, 'meal_review', 'meal', ['meal_id'], ['id'], ondelete='CASCADE')
    op.drop_column('meal_review', 'meal_name')
    op.drop_column('meal_review', 'place_id')
    op.add_column('place', sa.Column('cuisine', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'cuisine')
    op.add_column('meal_review', sa.Column('place_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('meal_review', sa.Column('meal_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'meal_review', type_='foreignkey')
    op.create_foreign_key('meal_review_place_id_fkey', 'meal_review', 'place', ['place_id'], ['id'])
    op.drop_column('meal_review', 'meal_id')
    op.drop_table('meal')
    # ### end Alembic commands ###
