"""added test_id to models for test purposes

Revision ID: 88f522a15f46
Revises: 23f4df2127cb
Create Date: 2025-11-14 23:49:01.246813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88f522a15f46'
down_revision: Union[str, None] = '23f4df2127cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_review', sa.Column('test_id', sa.String(), nullable=True))
    op.alter_column('meal_review', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.add_column('place', sa.Column('test_id', sa.String(), nullable=True))
    op.add_column('swipe', sa.Column('test_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('swipe', 'test_id')
    op.drop_column('place', 'test_id')
    op.alter_column('meal_review', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('meal_review', 'test_id')
    # ### end Alembic commands ###
