"""Cuisine type enum

Revision ID: 48f5e9757ce3
Revises: 3f3ac79c9a6e
Create Date: 2025-11-23 23:32:29.124886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f5e9757ce3'
down_revision: Union[str, None] = '3f3ac79c9a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the enum type explicitly
    cuisine_enum = sa.Enum('italian', 'french', 'spanish', 'greek', 'british', 'chinese', 'japanese', 'korean', 'thai', 'vietnamese', 'indian', 'filipino', 'american', 'mexican', 'mediterranean', 'african', 'fusion', 'cafe', 'bakery', 'barbecue', 'seafood', 'vegetarian_vegan', 'other', 'unspecified', name='cuisine_type_enum')
    cuisine_enum.create(op.get_bind(), checkfirst=True)

    # Update existing values to 'unspecified' to avoid casting errors
    op.execute("UPDATE place SET cuisine = 'unspecified'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('place', 'cuisine',
               existing_type=sa.VARCHAR(),
               type_=cuisine_enum,
               nullable=False,
               postgresql_using="cuisine::cuisine_type_enum")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('place', 'cuisine',
               existing_type=sa.Enum('italian', 'french', 'spanish', 'greek', 'british', 'chinese', 'japanese', 'korean', 'thai', 'vietnamese', 'indian', 'filipino', 'american', 'mexican', 'mediterranean', 'african', 'fusion', 'cafe', 'bakery', 'barbecue', 'seafood', 'vegetarian_vegan', 'other', 'unspecified', name='cuisine_type_enum'),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###

    # Drop the enum type
    sa.Enum(name='cuisine_type_enum').drop(op.get_bind(), checkfirst=True)
