"""remove is_joined from user

Revision ID: 885ec04d5cd8
Revises: 85acb3ca8152
Create Date: 2025-11-11 14:12:06.585734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '885ec04d5cd8'
down_revision: Union[str, None] = '85acb3ca8152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'is_joined')
    op.drop_column('app_user', 'joined_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('joined_at', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('app_user', sa.Column('is_joined', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
