"""cousine is now nullabe

Revision ID: 7b1c2286a1e9
Revises: 5108bf487b2e
Create Date: 2025-11-25 15:46:14.047507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b1c2286a1e9'
down_revision: Union[str, None] = '5108bf487b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('place', 'cuisine',
               existing_type=postgresql.ENUM('italian', 'french', 'spanish', 'greek', 'british', 'chinese', 'japanese', 'korean', 'thai', 'vietnamese', 'indian', 'filipino', 'american', 'mexican', 'mediterranean', 'african', 'fusion', 'cafe', 'bakery', 'barbecue', 'seafood', 'vegetarian_vegan', 'other', 'unspecified', name='cuisine_type_enum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('place', 'cuisine',
               existing_type=postgresql.ENUM('italian', 'french', 'spanish', 'greek', 'british', 'chinese', 'japanese', 'korean', 'thai', 'vietnamese', 'indian', 'filipino', 'american', 'mexican', 'mediterranean', 'african', 'fusion', 'cafe', 'bakery', 'barbecue', 'seafood', 'vegetarian_vegan', 'other', 'unspecified', name='cuisine_type_enum'),
               nullable=False)
    # ### end Alembic commands ###
