"""some stuff

Revision ID: dad2dc48a56a
Revises: f521483e23d8
Create Date: 2025-11-12 15:04:51.578068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dad2dc48a56a'
down_revision: Union[str, None] = 'f521483e23d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_review_image', sa.Column('sequence_index', sa.Integer(), nullable=False))
    op.add_column('place_image', sa.Column('sequence_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place_image', 'sequence_index')
    op.drop_column('meal_review_image', 'sequence_index')
    # ### end Alembic commands ###
