def get_meals():
    return [
        {
            "test_id": "avocado-sandwich",
            "place_test_id": "kaist-duck-pond-cafe",
            "name": "Avocado Sandwich",
            "images": [
                "img_local/meals/brie-and-avocado-sandwich.jpg"
            ]
        },
        {
            "test_id": "spicy-chicken-burger",
            "place_test_id": "moms-touch-chicken",
            "name": "Spicy Chicken Burger",
        },
        {
            "test_id": "regular-chicken-set",
            "place_test_id": "moms-touch-chicken",
            "name": "Regular Chicken Set",
        },
        {
            "test_id": "pepperoni-pizza",
            "place_test_id": "pizza-school",
            "name": "Pepperoni Pizza",
        },
        {
            "test_id": "cheese-pizza",
            "place_test_id": "pizza-school",
            "name": "Cheese Pizza",
        },
        {
            "test_id": "veggie-supreme",
            "place_test_id": "pizza-school",
            "name": "Veggie Supreme",
        },
        {
            "test_id": "whopper",
            "place_test_id": "burger-king-kaist",
            "name": "Whopper",
        },
        {
            "test_id": "impossible-whopper",
            "place_test_id": "burger-king-kaist",
            "name": "Impossible Whopper",
        },
        {
            "test_id": "grilled-pork-belly-set",
            "place_test_id": "samgyeopsal-house",
            "name": "Grilled Pork Belly Set",
        },
        {
            "test_id": "spicy-pork-bulgogi",
            "place_test_id": "samgyeopsal-house",
            "name": "Spicy Pork Bulgogi",
        },
        {
            "test_id": "beef-short-rib",
            "place_test_id": "samgyeopsal-house",
            "name": "Beef Short Rib",
        },
        {
            "test_id": "caramel-macchiato",
            "place_test_id": "starbucks-kaist",
            "name": "Caramel Macchiato",
        },
        {
            "test_id": "americano",
            "place_test_id": "starbucks-kaist",
            "name": "Americano",
        },
        {
            "test_id": "egg-cheese-sandwich",
            "place_test_id": "starbucks-kaist",
            "name": "Egg & Cheese Sandwich",
        },
        {
            "test_id": "honey-combo",
            "place_test_id": "kyochon-chicken",
            "name": "Honey Combo",
        },
        {
            "test_id": "red-combo-spicy",
            "place_test_id": "kyochon-chicken",
            "name": "Red Combo (Spicy)",
        },
        {
            "test_id": "abalone-porridge",
            "place_test_id": "bon-juk-restaurant",
            "name": "Abalone Porridge",
        },
        {
            "test_id": "pumpkin-porridge",
            "place_test_id": "bon-juk-restaurant",
            "name": "Pumpkin Porridge",
        },
        {
            "test_id": "veggie-delite",
            "place_test_id": "subway-kaist",
            "name": "Veggie Delite",
        },
        {
            "test_id": "italian-bmt",
            "place_test_id": "subway-kaist",
            "name": "Italian BMT",
        },
        {
            "test_id": "brown-sugar-pearl-milk-tea",
            "place_test_id": "gongcha-bubbletea",
            "name": "Brown Sugar Pearl Milk Tea",
        },
        {
            "test_id": "mango-green-tea",
            "place_test_id": "gongcha-bubbletea",
            "name": "Mango Green Tea",
        },
        {
            "test_id": "belgian-waffle",
            "place_test_id": "caffe-bene-kaist",
            "name": "Belgian Waffle",
        },
        {
            "test_id": "croissant",
            "place_test_id": "paris-baguette-kaist",
            "name": "Croissant",
        },
        {
            "test_id": "strawberry-cake-slice",
            "place_test_id": "paris-baguette-kaist",
            "name": "Strawberry Cake Slice",
        },
        {
            "test_id": "golden-olive-fried-chicken",
            "place_test_id": "bbq-chicken-daehak",
            "name": "Golden Olive Fried Chicken",
        },
        {
            "test_id": "gangjeong-chicken",
            "place_test_id": "bbq-chicken-daehak",
            "name": "Gangjeong Chicken",
        },
        {
            "test_id": "tiramisu-cake",
            "place_test_id": "twosome-place",
            "name": "Tiramisu Cake",
        },
        {
            "test_id": "iced-latte",
            "place_test_id": "twosome-place",
            "name": "Iced Latte",
        },
        {
            "test_id": "supreme-pizza",
            "place_test_id": "dominos-pizza-kaist",
            "name": "Supreme Pizza",
        },
        {
            "test_id": "bulgogi-burger",
            "place_test_id": "lotteria-fastfood",
            "name": "Bulgogi Burger",
        },
        {
            "test_id": "shrimp-burger",
            "place_test_id": "lotteria-fastfood",
            "name": "Shrimp Burger",
        },
        {
            "test_id": "tuna-kimbap",
            "place_test_id": "kimbap-heaven",
            "name": "Tuna Kimbap",
        },
        {
            "test_id": "kimchi-fried-rice",
            "place_test_id": "kimbap-heaven",
            "name": "Kimchi Fried Rice",
        },
        {
            "test_id": "spicy-ramen",
            "place_test_id": "kimbap-heaven",
            "name": "Spicy Ramen",
        },
        {
            "test_id": "pretzel-cinnamon",
            "place_test_id": "tom-n-toms",
            "name": "Pretzel Cinnamon",
        },
        {
            "test_id": "cold-brew",
            "place_test_id": "ediya-coffee",
            "name": "Cold Brew",
        },
        {
            "test_id": "blueberry-smoothie",
            "place_test_id": "ediya-coffee",
            "name": "Blueberry Smoothie",
        },
        {
            "test_id": "vanilla-latte",
            "place_test_id": "angelinus-coffee",
            "name": "Vanilla Latte",
        },
    ]

def get_reviews():

    return [
        {
            "test_id": "avocado-sandwich-1",
            "place_test_id": "kaist-duck-pond-cafe",
            "meal_test_id": "avocado-sandwich",
            "rating": 4,
            "text": "Fresh and tasty sandwich with a nice view of the pond.",
            "waiting_time_minutes": 10,
            "price": 7000,
            "is_vegan": "yes",
            "is_halal": "unspecified",
            "is_vegetarian": "yes",
            "is_spicy": "no",
            "is_gluten_free": "unspecified",
            "is_dairy_free": "unspecified",
            "is_nut_free": "no",
            "images": [
                "img_local/reviews/chicken-avocado-sandwich.jpg"
            ]
        },
        {
            "test_id": "spicy-chicken-burger-1",
            "place_test_id": "moms-touch-chicken",
            "meal_test_id": "spicy-chicken-burger",
            "rating": 5,
            "text": "🔥🔥🔥 ABSOLUTELY AMAZING! The spice level is perfect and the chicken is so crispy!\n\nI come here at least twice a week. Best chicken burger in Daejeon hands down. The staff is super friendly too!",
            "waiting_time_minutes": 15,
            "price": 6500,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "no",
            "is_spicy": "yes",
            "is_gluten_free": "no",
            "is_dairy_free": "unspecified",
            "is_nut_free": "unspecified",
            "images": [
                "img_local/reviews/spicy-chicken-sandwich.jpg"
            ]
        },
        {
            "test_id": "regular-chicken-set-1",
            "place_test_id": "moms-touch-chicken",
            "meal_test_id": "regular-chicken-set",
            "rating": 4,
            "text": "Good chicken, reasonable price",
            "price": 8900,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "no",
            "is_spicy": "no",
            "is_gluten_free": "unspecified",
            "is_dairy_free": "yes",
            "is_nut_free": "yes",
            "images": [
                "img_local/reviews/korean-chicken-platter.jpg"
            ]
        },
        {
            "test_id": "pepperoni-pizza-1",
            "place_test_id": "pizza-school",
            "meal_test_id": "pepperoni-pizza",
            "rating": 3,
            "text": "정말 맛있어요! 가격도 저렴하고 양도 많아요. 학생들한테 완벽한 선택입니다 👍",
            "waiting_time_minutes": 20,
            "price": 5900,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "no",
            "is_spicy": "no",
            "is_gluten_free": "no",
            "is_dairy_free": "no",
            "is_nut_free": "yes",
            "images": [
                "img_local/reviews/pepperoni-pizza-so-good.jpg",
                "img_local/reviews/ci-troviamo-nel-cuore.jpg"
            ]
        },
        {
            "test_id": "cheese-pizza-1",
            "place_test_id": "pizza-school",
            "meal_test_id": "cheese-pizza",
            "rating": 2,
            "text": "Way too greasy and the cheese tasted cheap. Not worth it even for the low price.",
            "waiting_time_minutes": 18,
            "price": 4900,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "yes",
            "is_spicy": "no",
            "is_gluten_free": "no",
            "is_dairy_free": "no",
            "is_nut_free": "yes",
            "images": [
                "img_local/reviews/14-inch-cheese-pizza.jpg"
            ]
        },
        {
            "test_id": "veggie-supreme-1",
            "place_test_id": "pizza-school",
            "meal_test_id": "veggie-supreme",
            "rating": 4,
            "text": "Actually pretty decent for a budget pizza place! Lots of vegetables and fresh ingredients.",
            "waiting_time_minutes": 22,
            "price": 6500,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "yes",
            "is_spicy": "no",
            "is_gluten_free": "unspecified",
            "is_dairy_free": "no",
            "is_nut_free": "unspecified",
            "images": [
                "img_local/reviews/domino-s-veggie-supreme.jpg"
            ]
        },
        {
            "test_id": "whopper-1",
            "place_test_id": "burger-king-kaist",
            "meal_test_id": "whopper",
            "rating": 3,
            "text": "Standard BK experience",
            "waiting_time_minutes": 8,
            "price": 7200,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "no",
            "is_spicy": "no",
            "is_gluten_free": "unspecified",
            "is_dairy_free": "unspecified",
            "is_nut_free": "unspecified",
            "images": [
                "img_local/reviews/whopper-and-fries-both.jpg"
            ]
        },
        {
            "test_id": "impossible-whopper-1",
            "place_test_id": "burger-king-kaist",
            "meal_test_id": "impossible-whopper",
            "rating": 4,
            "text": "Finally a decent vegetarian option at a fast food place! Tastes surprisingly close to the real thing.",
            "waiting_time_minutes": 10,
            "price": 8500,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "yes",
            "is_spicy": "no",
            "is_gluten_free": "unspecified",
            "is_dairy_free": "no",
            "is_nut_free": "yes",
            "images": [
                "img_local/reviews/the-full-meal-sorry-no.jpg"
            ]
        },
        {
            "test_id": "grilled-pork-belly-set-1",
            "place_test_id": "samgyeopsal-house",
            "meal_test_id": "grilled-pork-belly-set",
            "rating": 5,
            "text": "삼겹살이 정말 두껍고 맛있어요! 같이 나오는 반찬들도 훌륭하고 사장님이 친절하세요.\n\n가격 대비 최고의 선택입니다. 친구들이랑 자주 옵니다 😊",
            "waiting_time_minutes": 5,
            "price": 13000,
            "is_vegan": "no",
            "is_halal": "no",
            "is_vegetarian": "no",
            "is_spicy": "no",
            "is_gluten_free": "yes",
            "is_dairy_free": "yes",
            "is_nut_free": "yes",
            "images": [
                "img_local/reviews/grilled pork belly.jpg"
            ]
        },
        {
            "test_id": "spicy-pork-bulgogi-1",
            "place_test_id": "samgyeopsal-house",
            "meal_test_id": "spicy-pork-bulgogi",
            "rating": 4,
            "text": "Good spice level and flavor!",
            "waiting_time_minutes": 7,
            "price": 11000,
            "is_vegan": "no",
            "is_halal": "no",
            "is_vegetarian": "no",
            "is_spicy": "yes",
            "is_gluten_free": "no",
            "is_dairy_free": "yes",
            "is_nut_free": "yes",
            "images": [
                "img_local/reviews/Spicy Pork Bulgogi.jpg",
                "img_local/reviews/Spicy Pork Bulgogi 2.jpg"
            ]
        },
        {
            "test_id": "beef-short-rib-1",
            "place_test_id": "samgyeopsal-house",
            "meal_test_id": "beef-short-rib",
            "rating": 5,
            "text": "Expensive but worth every won. The meat is incredibly tender and well-marinated. Service is excellent - they grill it for you perfectly.",
            "waiting_time_minutes": 10,
            "price": 18000,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "no",
            "is_spicy": "no",
            "is_gluten_free": "unspecified",
            "is_dairy_free": "yes",
            "is_nut_free": "unspecified",
            "images": [
                "img_local/reviews/braised-beef-short-ribs.jpg"
            ]
        },
        {
            "test_id": "caramel-macchiato-1",
            "place_test_id": "starbucks-kaist",
            "meal_test_id": "caramel-macchiato",
            "rating": 3,
            "text": "너무 달아요",
            "price": 5600,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "yes",
            "is_spicy": "no",
            "is_gluten_free": "unspecified",
            "is_dairy_free": "no",
            "is_nut_free": "unspecified",
            "images": [
                "img_local/reviews/caramel mach.jpeg"
            ]
        },
        {
            "test_id": "americano-1",
            "place_test_id": "starbucks-kaist",
            "meal_test_id": "americano",
            "rating": 4,
            "text": "Reliable coffee when I need to study",
            "waiting_time_minutes": 5,
            "price": 4500,
            "is_vegan": "yes",
            "is_halal": "yes",
            "is_vegetarian": "yes",
            "is_spicy": "no",
            "is_gluten_free": "yes",
            "is_dairy_free": "yes",
            "is_nut_free": "yes",
            "images": [
                "img_local/reviews/americano.jpeg"
            ]
        },
        {
            "test_id": "egg-cheese-sandwich-1",
            "place_test_id": "starbucks-kaist",
            "meal_test_id": "egg-cheese-sandwich",
            "rating": 2,
            "text": "Overpriced and underwhelming. The bread was dry and the egg was rubbery. For 5500 won I expected much better quality.\n\nNot worth it at all.",
            "waiting_time_minutes": 12,
            "price": 5500,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "yes",
            "is_spicy": "no",
            "is_gluten_free": "unspecified",
            "is_dairy_free": "unspecified",
            "is_nut_free": "unspecified",
            "images": [
                "img_local/reviews/egg cheese sand.jpeg"
            ]
        },
        {
            "test_id": "honey-combo-1",
            "place_test_id": "kyochon-chicken",
            "meal_test_id": "honey-combo",
            "rating": 5,
            "text": "🍗 THE BEST CHICKEN IN KOREA! No debate!\n\nPerfectly crispy outside, juicy inside. The honey glaze is addictive. I literally dream about this chicken.",
            "waiting_time_minutes": 25,
            "price": 19000,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "no",
            "is_spicy": "no",
            "is_gluten_free": "unspecified",
            "is_dairy_free": "yes",
            "is_nut_free": "unspecified",
            "images": [
                "img_local/reviews/honey chick.jpeg"
            ]
        },
        {
            "test_id": "red-combo-(spicy)-1",
            "place_test_id": "kyochon-chicken",
            "meal_test_id": "red-combo-spicy",
            "rating": 4,
            "text": "진짜 매워요! 하지만 맛있어요 🔥",
            "waiting_time_minutes": 30,
            "price": 19000,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "no",
            "is_spicy": "yes",
            "is_gluten_free": "unspecified",
            "is_dairy_free": "unspecified",
            "is_nut_free": "yes",
        },
        {
            "test_id": "abalone-porridge-1",
            "place_test_id": "bon-juk-restaurant",
            "meal_test_id": "abalone-porridge",
            "rating": 5,
            "text": "Perfect comfort food when you're sick or just want something warm and nourishing. The abalone is real and the porridge is smooth and flavorful.\n\nHighly recommended!",
            "waiting_time_minutes": 15,
            "price": 9500,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "no",
            "is_spicy": "no",
            "is_gluten_free": "yes",
            "is_dairy_free": "yes",
            "is_nut_free": "yes",
        },
        {
            "test_id": "pumpkin-porridge-1",
            "place_test_id": "bon-juk-restaurant",
            "meal_test_id": "pumpkin-porridge",
            "rating": 4,
            "text": "Healthy and delicious",
            "waiting_time_minutes": 12,
            "price": 7000,
            "is_vegan": "yes",
            "is_halal": "yes",
            "is_vegetarian": "yes",
            "is_spicy": "no",
            "is_gluten_free": "yes",
            "is_dairy_free": "yes",
            "is_nut_free": "yes",
        },
        {
            "test_id": "veggie-delite-1",
            "place_test_id": "subway-kaist",
            "meal_test_id": "veggie-delite",
            "rating": 3,
            "text": "It's just vegetables on bread. Nothing special but at least it's fresh.",
            "waiting_time_minutes": 5,
            "price": 4800,
            "is_vegan": "unspecified",
            "is_halal": "unspecified",
            "is_vegetarian": "yes",
            "is_spicy": "no",
            "is_gluten_free": "unspecified",
            "is_dairy_free": "unspecified",
            "is_nut_free": "unspecified",
        },
        {
            "test_id": "italian-bmt-1",
            "place_test_id": "subway-kaist",
            "meal_test_id": "italian-bmt",
            "rating": 1,
            "text": "WORST SUBWAY I'VE EVER BEEN TO!!!\n\nThe meat was old and smelled weird. The bread was stale. Staff was rude when I complained.\n\nNEVER COMING BACK. Reported to management.",
            "waiting_time_minutes": 8,
            "price": 6500,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "no",
            "is_spicy": "no",
            "is_gluten_free": "unspecified",
            "is_dairy_free": "unspecified",
            "is_nut_free": "unspecified",
        },
        {
            "test_id": "brown-sugar-pearl-milk-tea-1",
            "place_test_id": "gongcha-bubbletea",
            "meal_test_id": "brown-sugar-pearl-milk-tea",
            "rating": 5,
            "text": "😍 Perfect sweetness and the pearls are so chewy! My go-to bubble tea spot.",
            "waiting_time_minutes": 10,
            "price": 5500,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "yes",
            "is_spicy": "no",
            "is_gluten_free": "yes",
            "is_dairy_free": "no",
            "is_nut_free": "yes",
        },
        {
            "test_id": "mango-green-tea-1",
            "place_test_id": "gongcha-bubbletea",
            "meal_test_id": "mango-green-tea",
            "rating": 4,
            "text": "Refreshing and not too sweet",
            "waiting_time_minutes": 7,
            "price": 5000,
            "is_vegan": "yes",
            "is_halal": "yes",
            "is_vegetarian": "yes",
            "is_spicy": "no",
            "is_gluten_free": "yes",
            "is_dairy_free": "yes",
            "is_nut_free": "yes",
        },
        {
            "test_id": "belgian-waffle-1",
            "place_test_id": "caffe-bene-kaist",
            "meal_test_id": "belgian-waffle",
            "rating": 4,
            "text": "와플이 겉은 바삭하고 속은 부드러워요. 아이스크림이랑 같이 먹으면 완벽해요!",
            "waiting_time_minutes": 15,
            "price": 7800,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "yes",
            "is_spicy": "no",
            "is_gluten_free": "unspecified",
            "is_dairy_free": "no",
            "is_nut_free": "unspecified",
        },
        {
            "test_id": "croissant-1",
            "place_test_id": "paris-baguette-kaist",
            "meal_test_id": "croissant",
            "rating": 3,
            "text": "Decent but nothing amazing. Good for a quick breakfast.",
            "price": 2800,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "yes",
            "is_spicy": "no",
            "is_gluten_free": "no",
            "is_dairy_free": "unspecified",
            "is_nut_free": "unspecified",
        },
        {
            "test_id": "strawberry-cake-slice-1",
            "place_test_id": "paris-baguette-kaist",
            "meal_test_id": "strawberry-cake-slice",
            "rating": 5,
            "text": "The cream is so light and fluffy! Fresh strawberries and the sponge cake is perfectly moist.\n\nWorth the calories 🍰✨",
            "waiting_time_minutes": 3,
            "price": 6500,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "yes",
            "is_spicy": "no",
            "is_gluten_free": "no",
            "is_dairy_free": "no",
            "is_nut_free": "yes",
        },
        {
            "test_id": "golden-olive-fried-chicken-1",
            "place_test_id": "bbq-chicken-daehak",
            "meal_test_id": "golden-olive-fried-chicken",
            "rating": 4,
            "text": "Really good! Crispy and the olive oil makes it feel a bit less guilty to eat 😅",
            "waiting_time_minutes": 28,
            "price": 18000,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "no",
            "is_spicy": "no",
            "is_gluten_free": "unspecified",
            "is_dairy_free": "unspecified",
            "is_nut_free": "yes",
        },
        {
            "test_id": "gangjeong-chicken-1",
            "place_test_id": "bbq-chicken-daehak",
            "meal_test_id": "gangjeong-chicken",
            "rating": 3,
            "text": "너무 달아서 좀 느끼해요",
            "waiting_time_minutes": 25,
            "price": 19000,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "no",
            "is_spicy": "no",
            "is_gluten_free": "unspecified",
            "is_dairy_free": "yes",
            "is_nut_free": "unspecified",
        },
        {
            "test_id": "tiramisu-cake-1",
            "place_test_id": "twosome-place",
            "meal_test_id": "tiramisu-cake",
            "rating": 5,
            "text": "INCREDIBLE! The best tiramisu outside of Italy I swear! The coffee flavor is strong and the mascarpone is perfect.\n\nA bit pricey but absolutely worth it for special occasions.",
            "waiting_time_minutes": 5,
            "price": 7200,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "yes",
            "is_spicy": "no",
            "is_gluten_free": "no",
            "is_dairy_free": "no",
            "is_nut_free": "yes",
        },
        {
            "test_id": "iced-latte-1",
            "place_test_id": "twosome-place",
            "meal_test_id": "iced-latte",
            "rating": 3,
            "text": "Average coffee, overpriced",
            "waiting_time_minutes": 8,
            "price": 5200,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "yes",
            "is_spicy": "no",
            "is_gluten_free": "yes",
            "is_dairy_free": "unspecified",
            "is_nut_free": "unspecified",
        },
        {
            "test_id": "supreme-pizza-1",
            "place_test_id": "dominos-pizza-kaist",
            "meal_test_id": "supreme-pizza",
            "rating": 2,
            "text": "Cold when it arrived and the toppings were sparse. Not worth 20,000 won at all. Very disappointed.",
            "waiting_time_minutes": 45,
            "price": 20000,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "no",
            "is_spicy": "no",
            "is_gluten_free": "unspecified",
            "is_dairy_free": "unspecified",
            "is_nut_free": "unspecified",
        },
        {
            "test_id": "bulgogi-burger-1",
            "place_test_id": "lotteria-fastfood",
            "meal_test_id": "bulgogi-burger",
            "rating": 3,
            "text": "한국식 불고기가 들어간 버거. 독특하긴 한데 그냥 그래요.",
            "waiting_time_minutes": 10,
            "price": 5800,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "no",
            "is_spicy": "no",
            "is_gluten_free": "unspecified",
            "is_dairy_free": "unspecified",
            "is_nut_free": "unspecified",
        },
        {
            "test_id": "shrimp-burger-1",
            "place_test_id": "lotteria-fastfood",
            "meal_test_id": "shrimp-burger",
            "rating": 4,
            "text": "Better than expected! The shrimp patty is actually quite good and crunchy.",
            "waiting_time_minutes": 12,
            "price": 6200,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "no",
            "is_spicy": "no",
            "is_gluten_free": "unspecified",
            "is_dairy_free": "no",
            "is_nut_free": "unspecified",
        },
        {
            "test_id": "tuna-kimbap-1",
            "place_test_id": "kimbap-heaven",
            "meal_test_id": "tuna-kimbap",
            "rating": 5,
            "text": "AMAZING VALUE! Only 3000 won and it's delicious and filling. Perfect student food.\n\nI eat here almost every day 🍙",
            "waiting_time_minutes": 5,
            "price": 3000,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "no",
            "is_spicy": "no",
            "is_gluten_free": "no",
            "is_dairy_free": "yes",
            "is_nut_free": "yes",
        },
        {
            "test_id": "kimchi-fried-rice-1",
            "place_test_id": "kimbap-heaven",
            "meal_test_id": "kimchi-fried-rice",
            "rating": 4,
            "text": "김치볶음밥 최고! 가격도 싸고 맛도 좋아요 👍",
            "waiting_time_minutes": 8,
            "price": 4500,
            "is_vegan": "no",
            "is_halal": "no",
            "is_vegetarian": "no",
            "is_spicy": "yes",
            "is_gluten_free": "yes",
            "is_dairy_free": "yes",
            "is_nut_free": "yes",
        },
        {
            "test_id": "spicy-ramen-1",
            "place_test_id": "kimbap-heaven",
            "meal_test_id": "spicy-ramen",
            "rating": 3,
            "text": "Basic instant ramen but convenient when you're in a rush",
            "waiting_time_minutes": 7,
            "price": 3500,
            "is_vegan": "unspecified",
            "is_halal": "unspecified",
            "is_vegetarian": "unspecified",
            "is_spicy": "yes",
            "is_gluten_free": "no",
            "is_dairy_free": "unspecified",
            "is_nut_free": "unspecified",
        },
        {
            "test_id": "pretzel-cinnamon-1",
            "place_test_id": "tom-n-toms",
            "meal_test_id": "pretzel-cinnamon",
            "rating": 4,
            "text": "Warm, soft, and perfectly sweet. Great with their coffee!",
            "waiting_time_minutes": 10,
            "price": 4200,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "yes",
            "is_spicy": "no",
            "is_gluten_free": "no",
            "is_dairy_free": "no",
            "is_nut_free": "no",
        },
        {
            "test_id": "cold-brew-1",
            "place_test_id": "ediya-coffee",
            "meal_test_id": "cold-brew",
            "rating": 4,
            "text": "Smooth and strong. Best value coffee chain in Korea!",
            "waiting_time_minutes": 3,
            "price": 3000,
            "is_vegan": "yes",
            "is_halal": "yes",
            "is_vegetarian": "yes",
            "is_spicy": "no",
            "is_gluten_free": "yes",
            "is_dairy_free": "yes",
            "is_nut_free": "yes",
        },
        {
            "test_id": "blueberry-smoothie-1",
            "place_test_id": "ediya-coffee",
            "meal_test_id": "blueberry-smoothie",
            "rating": 2,
            "text": "Tasted artificial and was mostly ice. Not recommended.",
            "waiting_time_minutes": 6,
            "price": 4500,
            "is_vegan": "unspecified",
            "is_halal": "unspecified",
            "is_vegetarian": "yes",
            "is_spicy": "no",
            "is_gluten_free": "yes",
            "is_dairy_free": "unspecified",
            "is_nut_free": "unspecified",
        },
        {
            "test_id": "vanilla-latte-1",
            "place_test_id": "angelinus-coffee",
            "meal_test_id": "vanilla-latte",
            "rating": 3,
            "text": "ok",
            "price": 5100,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "yes",
            "is_spicy": "no",
            "is_gluten_free": "unspecified",
            "is_dairy_free": "unspecified",
            "is_nut_free": "unspecified",
        },
        {
            "test_id": "spicy-chicken-burger-2",
            "place_test_id": "moms-touch-chicken",
            "meal_test_id": "spicy-chicken-burger",
            "rating": 3,
            "text": "It was okay, but a bit too spicy for my taste. The chicken was quality though.",
            "waiting_time_minutes": 10,
            "price": 6500,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "no",
            "is_spicy": "yes",
            "is_gluten_free": "no",
            "is_dairy_free": "unspecified",
            "is_nut_free": "unspecified",
        },
        {
            "test_id": "pepperoni-pizza-2",
            "place_test_id": "pizza-school",
            "meal_test_id": "pepperoni-pizza",
            "rating": 5,
            "text": "Best value pizza around campus. Can't beat the price.",
            "waiting_time_minutes": 15,
            "price": 5900,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "no",
            "is_spicy": "no",
            "is_gluten_free": "no",
            "is_dairy_free": "no",
            "is_nut_free": "yes",
        },
        {
            "test_id": "honey-combo-2",
            "place_test_id": "kyochon-chicken",
            "meal_test_id": "honey-combo",
            "rating": 4,
            "text": "Delicious but the wait time was quite long on a Friday night.",
            "waiting_time_minutes": 45,
            "price": 19000,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "no",
            "is_spicy": "no",
            "is_gluten_free": "unspecified",
            "is_dairy_free": "yes",
            "is_nut_free": "unspecified",
        },
        {
            "test_id": "tuna-kimbap-2",
            "place_test_id": "kimbap-heaven",
            "meal_test_id": "tuna-kimbap",
            "rating": 4,
            "text": "Simple, fresh, and filling. Good for a quick lunch.",
            "waiting_time_minutes": 3,
            "price": 3000,
            "is_vegan": "no",
            "is_halal": "unspecified",
            "is_vegetarian": "no",
            "is_spicy": "no",
            "is_gluten_free": "no",
            "is_dairy_free": "yes",
            "is_nut_free": "yes",
        },
        {
            "test_id": "americano-2",
            "place_test_id": "starbucks-kaist",
            "meal_test_id": "americano",
            "rating": 5,
            "text": "My daily fuel. Consistent quality every time.",
            "waiting_time_minutes": 5,
            "price": 4500,
            "is_vegan": "yes",
            "is_halal": "yes",
            "is_vegetarian": "yes",
            "is_spicy": "no",
            "is_gluten_free": "yes",
            "is_dairy_free": "yes",
            "is_nut_free": "yes",
        },
    ]

def get_places_img_index():
    return {
        "generic-pizza": [
            "img_local/generic-pizza-1.jpg",
            "img_local/generic-pizza-2.jpg",
            "img_local/generic-pizza-3.jpg",
        ],
        "generic-burger": [
            "img_local/generic-burger-1.jpg",
            "img_local/generic-burger-2.jpg",
        ],
        "generic-cafe": [
            "img_local/generic-cafe-1.jpg",
            "img_local/generic-cafe-2.jpg",
        ],
        "generic-chicken": [
            "img_local/generic-chicken-1.jpg",
            "img_local/generic-chicken-2.jpg",
        ],
        "generic-korean-bbq": [
            "img_local/generic-korean-bbq-1.jpg",
            "img_local/generic-korean-bbq-2.jpg",
        ],

    }


def get_places():
    """
    AI GENERATED TEST DATA FOR PLACES
    """
    img_index = get_places_img_index()

    return [
        {
            "name": "KAIST Duck Pond Cafe",
            "address": "291 Daehak-ro, Yuseong-gu, Daejeon",
            "latitude": 36.3714,
            "longitude": 127.3650,
            "test_id": "kaist-duck-pond-cafe",
            "cuisine": "cafe",
            "images": img_index["generic-cafe"],
        },
        {
            "name": "Bon Juk Korean Restaurant",
            "address": "193 Daehak-ro, Yuseong-gu, Daejeon",
            "latitude": 36.3685,
            "longitude": 127.3590,
            "test_id": "bon-juk-restaurant",
            "cuisine": "korean",
        },
        {
            "name": "Subway KAIST Station",
            "address": "335 Gwahak-ro, Yuseong-gu, Daejeon",
            "latitude": 36.3742,
            "longitude": 127.3688,
            "test_id": "subway-kaist",
            "cuisine": "american",
        },
        {
            "name": "Mom's Touch Chicken",
            "address": "217 Daehak-ro, Yuseong-gu, Daejeon",
            "latitude": 36.3695,
            "longitude": 127.3605,
            "test_id": "moms-touch-chicken",
            "cuisine": "korean",
            "images": img_index["generic-chicken"],
        },
        {
            "name": "Gongcha Bubble Tea",
            "address": "201 Daehak-ro, Yuseong-gu, Daejeon",
            "latitude": 36.3690,
            "longitude": 127.3598,
            "test_id": "gongcha-bubbletea",
            "cuisine": "cafe",
        },
        {
            "name": "Caffe Bene KAIST",
            "address": "291 Daehak-ro, Yuseong-gu, Daejeon",
            "latitude": 36.3720,
            "longitude": 127.3655,
            "test_id": "caffe-bene-kaist",
            "cuisine": "cafe",
        },
        {
            "name": "Kyochon Chicken",
            "address": "225 Daehak-ro, Yuseong-gu, Daejeon",
            "latitude": 36.3700,
            "longitude": 127.3612,
            "test_id": "kyochon-chicken",
            "cuisine": "korean",
        },
        {
            "name": "Paris Baguette KAIST",
            "address": "195 Daehak-ro, Yuseong-gu, Daejeon",
            "latitude": 36.3688,
            "longitude": 127.3593,
            "test_id": "paris-baguette-kaist",
            "cuisine": "bakery",
        },
        {
            "name": "BBQ Chicken Daehak",
            "address": "209 Daehak-ro, Yuseong-gu, Daejeon",
            "latitude": 36.3693,
            "longitude": 127.3602,
            "test_id": "bbq-chicken-daehak",
            "cuisine": "korean",
        },
        {
            "name": "Burger King KAIST",
            "address": "305 Gwahak-ro, Yuseong-gu, Daejeon",
            "latitude": 36.3730,
            "longitude": 127.3670,
            "test_id": "burger-king-kaist",
            "cuisine": "american",
            "images": img_index["generic-burger"],
        },
        {
            "name": "Twosome Place Coffee",
            "address": "213 Daehak-ro, Yuseong-gu, Daejeon",
            "latitude": 36.3698,
            "longitude": 127.3608,
            "test_id": "twosome-place",
            "cuisine": "cafe",
        },
        {
            "name": "Pizza School",
            "address": "189 Daehak-ro, Yuseong-gu, Daejeon",
            "latitude": 36.3682,
            "longitude": 127.3585,
            "test_id": "pizza-school",
            "cuisine": "american",
            "images": img_index["generic-pizza"],
        },
        {
            "name": "Starbucks KAIST Campus",
            "address": "291 Daehak-ro, Yuseong-gu, Daejeon",
            "latitude": 36.3716,
            "longitude": 127.3652,
            "test_id": "starbucks-kaist",
            "cuisine": "cafe",
        },
        {
            "name": "Korean BBQ House Samgyeopsal",
            "address": "221 Daehak-ro, Yuseong-gu, Daejeon",
            "latitude": 36.3702,
            "longitude": 127.3615,
            "test_id": "samgyeopsal-house",
            "cuisine": "korean",
            "images": img_index["generic-korean-bbq"],
        },
        {
            "name": "Angel-in-us Coffee",
            "address": "197 Daehak-ro, Yuseong-gu, Daejeon",
            "latitude": 36.3686,
            "longitude": 127.3595,
            "test_id": "angelinus-coffee",
            "cuisine": "cafe",
        },
        {
            "name": "Lotteria Fast Food",
            "address": "205 Daehak-ro, Yuseong-gu, Daejeon",
            "latitude": 36.3692,
            "longitude": 127.3600,
            "test_id": "lotteria-fastfood",
            "cuisine": "american",
        },
        {
            "name": "Kimbap Heaven",
            "address": "185 Daehak-ro, Yuseong-gu, Daejeon",
            "latitude": 36.3680,
            "longitude": 127.3582,
            "test_id": "kimbap-heaven",
            "cuisine": "korean",
        },
        {
            "name": "Tom N Toms Coffee",
            "address": "229 Daehak-ro, Yuseong-gu, Daejeon",
            "latitude": 36.3705,
            "longitude": 127.3618,
            "test_id": "tom-n-toms",
            "cuisine": "cafe",
        },
        {
            "name": "Ediya Coffee Shop",
            "address": "191 Daehak-ro, Yuseong-gu, Daejeon",
            "latitude": 36.3684,
            "longitude": 127.3588,
            "test_id": "ediya-coffee",
            "cuisine": "cafe",
        },
        {
            "name": "Domino's Pizza KAIST",
            "address": "311 Gwahak-ro, Yuseong-gu, Daejeon",
            "latitude": 36.3735,
            "longitude": 127.3675,
            "test_id": "dominos-pizza-kaist",
            "cuisine": "american",
        },
    ]
